settings:
  title: 'Status Page'
  url: 'https://status.tormakristof.eu' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: webgateway # unique identifier
    name: webgateway.tormakristof.eu
    description: 'On-prem webgateway status' # default=empty
    url: 'https://tormakristof.eu/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: vzelenka
    name: vzelenka.tormakristof.eu
    description: 'vZelenka status'
    url: 'https://neko.tormakristof.eu'
    method: GET
    expectStatus: 401
    linkable: true # allows the title to be a link, default=true
